baseURL = "https://reef-pi.github.io/"
DefaultContentLanguage = "en-us"
theme = "hugo-sustain"
googleAnalytics = "UA-102968086-1"

[params]
Author = "Ranjib Dey"
Description = "reef-pi - An opensource reef tank controller based on Raspberry Pi"
custom_css = ["css/img.css"]

[params.social]
  Github    = "reef-pi"
  Email     = "info@reef-pi.com"
  Twitter   = "reef_pi"

[[menu.main]]
  name = "guides"
  identifier = "guides"
  weight = 50
  url = "/guides/"

[[menu.main]]
  name = "additional documentation"
  identifier = "additional documentation"
  weight = 100
  url = "/additional-documentation/"
  
[languages]
  [languages.en-us]
    weight = 1
    LanguageName = "English"

    title = "reef-pi - An opensource reef tank controller based on Raspberry Pi"
  [languages.es-es]
    weight = 2
    LanguageName = "Español"
    title = "reef-pi - Un controlador para acuario marino basado en Raspberry Pi"
